In [2]:
import numpy as np

In [ ]:
# check version

print(np.__version__)

1.22.4


In [ ]:
# How to create 1D array

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# How to create a boolean arrray

np.full(9, True, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.ones(9, dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# How to extract items that satisfy a given condition from 1D array?

# Question : Extract all odd numbers from array

a = np.arange(10)
a[a%2 != 0]

array([1, 3, 5, 7, 9])

In [ ]:
# How to replace items that satisfy a condition with another value in numpy array?

# Question: Replace all odd numbers in arr with -1

b = np.arange(10)+1
print(b)
b[b%2 == 1] = -1
b

[ 1  2  3  4  5  6  7  8  9 10]


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [ ]:
# How to replace items that satisfy a condition without affecting the original array

# Replace all odd numbers in arr with -1 without changing arr

arr = np.arange(10)
print(arr)
out = arr.copy()
out[out%2 == 1] = -1
print(out)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#  How to reshape an array
#  Convert a 1D array to a 2D array with 2 rows

arr = np.arange(9)
print(arr.shape)

arr = arr.reshape(3, 3)
print(arr)
print(arr.shape)


(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [ ]:
# How to stack two arrays vertically
a = np.arange(4)
b = np.arange(4)
np.vstack([a, b])

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
 # How to stack two arrays horizontally

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print("a = ", a)
print("\nb = ", b)
print("\nhorizontal stack = \n" , np.hstack([a, b]))

a =  [[0 1 2 3 4]
 [5 6 7 8 9]]

b =  [[1 1 1 1 1]
 [1 1 1 1 1]]

horizontal stack = 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
#  How to generate custom sequences in numpy without hardcoding
a = [1, 2, 3]
b = np.repeat(a, 3)
np.tile(a, 3)
c = np.tile(a,3)

np.hstack([b, c])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
# How to get the common items between two python numpy arrays?

# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [20]:
# How to remove from one array those items that exist in another?

# From array a remove all items present in array b

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [23]:
# How to get the positions where elements of two arrays match

# Question: Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [29]:
# How to extract all numbers between a given range from a numpy array

# Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[ (a >= 5) & (a <= 10)]

array([ 6,  9, 10])