Universal functions(Ufuncs) - vectorized functions
* Aggregate functions/Reduction functions
* Logical functions

vectorization is used speed up the code by without using loop

In [2]:
import numpy as np

In [3]:
a = np.array([1,2 ,3, 4])
b = np.array([2, 3, 4, 5])
a+b

array([3, 5, 7, 9])

In [5]:
np.add(a, b)

array([3, 5, 7, 9])

In [9]:
#sum
a = np.arange(12).reshape(3, 4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [10]:
np.sum(a)

66

In [11]:
a.shape

(3, 4)

In [15]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [17]:
np.sum(a, axis=1)

array([ 6, 22, 38])

In [19]:
np.mean(a)

5.5

In [25]:
np.mean(a, axis = 0)

array([4., 5., 6., 7.])

In [24]:
np.mean(a, axis =1)

array([1.5, 5.5, 9.5])

In [26]:
np.min(a, axis = 1)

array([0, 4, 8])

In [ ]:
# Logical Functions

In [31]:
a = np.array([1,0,  2, 3,0, 4])
b = np.array([0 , 0])

In [30]:
# if there is any element in the array which is non-zero
print(a.any(), b.any())

True False


In [32]:
# if there is any element pair where certain condition is true

a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(a, b)

[1 2 3 4] [4 3 2 1]


In [37]:
a <= b  # <= is a vectorized operator

array([ True,  True,  True,  True])

In [34]:
np.any(a < b)

True

In [35]:
# check if condition is true for all cases
np.all(a < b)

False

In [36]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
np.all((a <= b) & (b <= c))

True

In [ ]:
# Sorting

In [45]:
a = np.array([2, 30, 41, 7, 17, 52])

In [46]:
np.sort(a)

array([ 2,  7, 17, 30, 41, 52])

In [47]:
np.argsort(a)  # returns index of elements in sorted order

array([0, 3, 4, 1, 2, 5])

In [49]:
a

array([ 2, 30, 41,  7, 17, 52])

In [ ]:
# sorting ? if axis is not provided, by default sort, argsort
# sorts the last dimension

In [51]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])
b = np.sort(a)
print(b)

[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]


In [53]:
c = np.sort(b , axis = 0 )
c

array([[  0,  12,  43],
       [  3,  23,  89],
       [  4,  69, 420]])

In [54]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /content/fitness.txt
100% 3.14k/3.14k [00:00<00:00, 12.7MB/s]


In [56]:
data = np.loadtxt("fitness.txt", dtype="str")

In [59]:
data.ndim

2

In [ ]:
# no of rows and no of columns

In [60]:
data.shape

(96, 7)

In [61]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [63]:
data.T.shape

(7, 96)

In [64]:
data.dtype

dtype('<U10')

In [65]:
type(data)

numpy.ndarray

In [68]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [69]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [70]:
date, step_count, mood, calories_burned, hours_of_sleep, activity_status, weight = data.T

In [71]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [75]:
a, b, c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [73]:
c

[7, 8, 9]

In [76]:
step_count.dtype

dtype('<U10')

In [80]:
step_count = np.array(step_count, dtype="int")
step_count.dtype   # we are converting it int so we can perform math operations

dtype('int64')

In [81]:
step_count.max()

7422

In [82]:
calories_burned = np.array(calories_burned, dtype = 'int')

hours_of_sleep = np.array(hours_of_sleep, dtype = 'int')

weight = np.array(weight, dtype = 'int')

In [83]:
mood  # categorical variable

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [84]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [86]:
# 100->Sad, 200->Neurtal, 300-->Happy

In [89]:
mood[mood == "100"]

array(['100', '100', '100', '100', '100', '100', '100', '100', '100',
       '100', '100', '100', '100', '100', '100', '100', '100', '100',
       '100', '100', '100', '100', '100', '100', '100', '100', '100',
       '100', '100'], dtype='<U10')

In [92]:
mood[mood == "100"] = "sad"

In [95]:
mood[mood == "200"] = "Neutral"
mood[mood == "300"] = "Happy"


In [96]:
mood  # data-munging, data-manipulation, data-cleaning

array(['Neutral', 'sad', 'sad', 'sad', 'Neutral', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'Happy', 'sad', 'sad', 'sad', 'sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'sad', 'Neutral', 'Neutral',
       'sad', 'sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'sad', 'Neutral', 'sad', 'Neutral', 'Neutral', 'sad', 'sad', 'sad',
       'sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'sad', 'sad', 'sad',
       'Neutral', 'Neutral', 'sad', 'sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [97]:
np.unique(mood)

array(['Happy', 'Neutral', 'sad'], dtype='<U10')

In [98]:
activity_status

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [99]:
activity_status[activity_status == '500'] = 'Active'
activity_status[activity_status == '0'] = 'Inactive'

In [100]:
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [ ]:
# insights from the data

In [102]:
# what is the average step count - step_count
np.mean(step_count)

2935.9375

In [ ]:
# On which date the step count was highest? step_count, date

In [106]:
date[np.argmax(step_count)]

'14-12-2017'

In [105]:
# What is the most frequent mood? ---> if given counts of all the mood, calculate most frequent

7422

In [124]:
len(mood[mood == "sad"])

29

In [108]:
len(mood[mood == "Happy"])

40

In [109]:
len(mood[mood == "Neutral"])

27

In [110]:
np.unique(mood, return_counts = True)

(array(['Happy', 'Neutral', 'sad'], dtype='<U10'), array([40, 27, 29]))

In [ ]:
# Does the step_count changes with mood?

In [121]:
np.mean(step_count[mood == "Neutral"])

3153.777777777778

In [125]:
np.mean(step_count[mood == "sad"])

2103.0689655172414

In [126]:
np.mean(step_count[mood == "Happy"])

3392.725

In [132]:
np.unique(mood[step_count < 500], return_counts = True)

(array(['Happy', 'Neutral', 'sad'], dtype='<U10'), array([4, 3, 8]))

In [ ]:
# Operations on arrays in Numpy

In [133]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
m1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [135]:
m1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [136]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 7])
a+b   # element wise addition

array([ 5,  7, 10])

In [137]:
a*b

array([ 4, 10, 21])

In [138]:
a = np.array([0,2,3])
b = np.array([1,3,5])
a >= b

array([False, False, False])

In [139]:
A = np.arange(12).reshape(3,4)
B = np.arange(12).reshape(3,4)

In [140]:
A*B # not matrix multiplication

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# (x1, y1) (x2, y2) matrix multiplication condition y1 == x2

In [141]:
B = B.reshape(4, 3)

In [145]:
B


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [143]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
A * B # (4, 3) (3, 4) y1 == x2
# this doesn't work because this is not matrix multiplication
# we are operating on shapes here

ValueError: ignored

In [147]:
np.matmul(A, B)  # matirx multiplication

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [148]:
A @ B # matirx multiplication

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [149]:
np.dot(A, B) # dot product works only with same no of elements

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [153]:
a= np.array([1,2,3])
b = np.array([1,1,1])
np.dot(a, b)

6

In [152]:
k = np.array([[1], [2]])
z = np.array([2])
np.dot(k, z)

array([2, 4])

In [154]:
A * 2 # Vectorisation

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# unfuncs provided by numpy

In [158]:
np.log(np.arange(1, 100))

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [155]:
import math

In [156]:
math.log(10)

2.302585092994046

In [157]:
math.log([1, 2, 3])

TypeError: ignored

In [159]:
np_log = np.vectorize(math.log)  # converted into a universal function

In [160]:
np_log(np.arange(1, 100, 10))

array([0.        , 2.39789527, 3.04452244, 3.4339872 , 3.71357207,
       3.93182563, 4.11087386, 4.26267988, 4.39444915, 4.51085951])

In [ ]:
# Broadcasting -
# where elements are repeated, so numpy operations can be performed

In [161]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
# repeats data in said dimension

In [162]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [164]:
a = np.tile(np.arange(0, 40, 10), (2, 2))
a


array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [165]:
a = np.arange(0, 4)
b = np.arange(12).reshape(3, 4)

In [166]:
print(a.shape, b.shape)

(4,) (3, 4)


In [169]:
a

array([0, 1, 2, 3])

In [170]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [171]:
a+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [177]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6).reshape(3, 2)

In [178]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [179]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [181]:
c + d
# here the elements cannot be repeated to be broadcasted

ValueError: ignored

In [183]:
a = np.arange(0, 40, 10).reshape(4, 1)
a.shape

(4, 1)

In [188]:
np.arange(0, 40, 10)#[:, np.newaxis]

array([[ 0],
       [10],
       [20],
       [30]])

In [190]:
a = np.arange(5)[np.newaxis]
a     # adds a new axis

array([[0, 1, 2, 3, 4]])