EDA - Exploratory data analysis.
each columns - feature.
each rows - datapoint.
all rows give us no of records.
all columns give us no of feature.
considering one feature is uni-variate analysis.
considering two feature is bi-variate analysis.
considering multi feature is multi-variate analysis.


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3, 4, 5]
a_sqrt = [element**2 for element in a] #element-wise operation

In [ ]:
a_sqrt


[1, 4, 9, 16, 25]

In [ ]:
a_np = np.array(a)
print(a_np**2)

[ 1  4  9 16 25]


In [ ]:
l = range(10000)
len(l)

10000

In [ ]:
%timeit [i**2 for i in l]

2.98 ms ± 79.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
l_np = np.arange(10000)


In [ ]:
len(l_np)

10000

In [ ]:
%timeit l_np**2

6.45 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


if you have to perform element-wise operation, Numpy provides
1. Clean Syntax
2. Computation Benefit

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
a.ndim #dimension

1

In [ ]:
a.shape # gives us the no of element accross the row

(3,)

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 5, 1.5) #valid for arange not range

array([1. , 2.5, 4. ])

In [ ]:
#start , end, count
np.linspace(0, 100, 9) # endpoint is inclusive

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [ ]:
# array, arange, linspace

In [ ]:
type(a_np)

numpy.ndarray

In [ ]:
arr = np.array([1, 2, 3, 4.2])
print(arr)
# it is a array so we cannot have different elements,
# so it will be converted to higher value which is float here

[1.  2.  3.  4.2]


In [ ]:
arr = np.array([1, 2, 3, 'abc']) # string
arr

array(['1', '2', '3', 'abc'], dtype='<U21')

In [ ]:
np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [ ]:
arr6 = np.array([0, 10, 100])
arr6**10

array([                  0,         10000000000, 7766279631452241920])

In [ ]:
np.array([0, 10, 100]).dtype

dtype('int64')

In [ ]:
# Working with 2D arrays

numpy.ndarray

In [ ]:
m1 = np.array([[1,2, 3], [4, 5, 6]])
print(m1.ndim, m1.shape)

2 (2, 3)


In [ ]:
len(m1)

2

In [ ]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a) # row vector

[[1 2 3 4 5]]


In [ ]:
print(a.ndim, a.shape)

2 (1, 5)


In [ ]:
m2 = np.arange(1, 13)
print(m2.ndim, m2.shape)

1 (12,)


In [ ]:
m2.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
# resize

In [ ]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
a.reshape(2, 4)

ValueError: ignored

In [ ]:
f = np.array([1,2,3, 4])
f.resize(2, 3)
print(f)  # fills with 0

[[1 2 3]
 [4 0 0]]


In [ ]:
k = np.array([1, 2, 3, 4])
np.resize(k, (2, 4)) # makes copy of original element

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
a = np.arange(3).reshape(1, 3)
print(a)

[[0 1 2]]


In [ ]:
a.T

array([[0],
       [1],
       [2]])

In [ ]:
# nd array --> flatten

In [ ]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(12).shape

(12,)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(6, -1) # here should 2 instead of -1 ,
#numpy automatically calculates it

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2, 3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# diagonal matrices
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
a = np.diag([1,2,3])
b = np.diag(a)
print(b)
# if we apply diag twice it get backs to its original

[1 2 3]


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Indexing and slicing

In [ ]:
m1 = np.arange(1,10).reshape((3,3))
print(m1)
m1[1][2] # not use this syntax

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [ ]:
m1[1, 2] # use this syntax

6

In [ ]:
m1 = np.array([100,200,300,400,500,600])

In [ ]:
m1[[2,3,4,1,2,2]]  #passing list of indexes

array([300, 400, 500, 200, 300, 300])

In [ ]:
m1 = np.arange(9).reshape((3,3))
m1[[0, 0, 1], [0, 1, 2]] # important

array([0, 1, 5])

In [ ]:
m1 = np.arange(12)
m1[:5]

array([0, 1, 2, 3, 4])

In [ ]:
m1 = np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])

m1[0, 1:3]

array([1, 2])

In [ ]:
m1[:, 2:]

array([10, 11])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
a

array([1, 2, 6, 7, 8])

In [ ]:
# fancy indexing- masking

In [ ]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1 < 6 # mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
m1[m1 < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
m1[m1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# divisible by 2 or 5

In [ ]:
a = np.arange(11)

In [ ]:
a[(a %2 == 0) | (a%5 == 0)]

array([ 0,  2,  4,  5,  6,  8, 10])

In [ ]:
a = np.arange(6)
mask = (a%2 == 0)
a[mask] = -1
print(a)

[-1  1 -1  3 -1  5]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print (a * b)

[1 4 9]


[4, 3, 2, 1]